
 
// auth
export const REGISTRO_EXITO = 'REGISTRO_EXITO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const LOGIN_EXITO = 'LOGIN_EXITO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// firebase
export const FB_CERRAR_SESION = 'CERRAR_SESION';
export const FB_USUARIO_AUTENTICADO = 'FB_USUARIO_AUTENTICADO';
export const FB_USUARIO_LOCAL = 'FB_USUARIO_LOCAL';

//usuarios
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const ORDENAR_FILTRAR_USUARIOS = 'ORDENAR_FILTRAR_USUARIOS';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';
export const DESELECCIONAR_USUARIO = 'DESELECCIONAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const CARGAR_COMBOS_USUARIO = 'CARGAR_COMBOS_SUBASTA';


// SubastaContext
export const OBTENER_SUBASTAS = 'OBTENER_SUBASTAS';
export const ORDENAR_FILTRAR_SUBASTAS = 'ORDENAR_FILTRAR_SUBASTAS';
export const ACTUALIZAR_SUBASTA = 'ACTUALIZAR_SUBASTA';
export const ELIMINAR_SUBASTA = 'ELIMINAR_SUBASTA';
export const SELECCIONAR_SUBASTA = 'SELECCIONAR_SUBASTA';
export const DESELECCIONAR_SUBASTA = 'DESELECCIONAR_SUBASTA';


export const AGREGAR_IMAGEN = 'AGREGAR_IMAGEN';
export const QUITAR_IMAGEN = 'QUITAR_IMAGEN';

export const CARGAR_COMBOS_SUBASTA = 'CARGAR_COMBOS_SUBASTA';

export const OBTENER_CATALOGO = 'OBTENER_CATALOGO';
export const SELECCIONAR_ITEM_CATALOGO = 'SELECCIONAR_ITEM_CATALOGO';
export const DESELECCIONAR_ITEM_CATALOGO = 'DESELECCIONAR_ITEM_CATALOGO';

export const SUBASTA_STATS = 'SUBASTA_STATS';
